# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
#  	sync_code_signing(type: "appstore")

    version = increment_version_number(bump_type: "patch", xcodeproj: "aircredit.xcodeproj")
    sh("echo", "Incremented version to " << version)
    sh("cd .. && xcrun agvtool new-version -all " << version, log: true)
    sh("cd .. && xcrun agvtool new-marketing-version " << version, log: true)

    get_certificates           # invokes cert
	  get_provisioning_profile   # invokes sigh

    build_app(workspace: "aircredit.xcworkspace", scheme: "aircredit")
    notification(subtitle: "Finished Building", message: "Ready to upload...", sound: "Purr")
    say("Build Complete")
    upload_to_testflight
    notification(subtitle: "Finished Uploading", message: "Ready to test...", sound: "Purr")
    say("Upload Complete")
  end
end
