# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
#  	sync_code_signing(type: "appstore")
    increment_build_number(xcodeproj: "aircredit.xcodeproj")
    get_certificates           # invokes cert
	get_provisioning_profile   # invokes sigh

    build_app(workspace: "aircredit.xcworkspace", scheme: "aircredit")
    changelog_from_git_commits
    upload_to_testflight(changelog: "Add rocket emoji")
    slack(message: "Successfully distributed a new beta build")
  end
end
