# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

############################# CONFIG     ################################

$appName = 'aircredit'
$appXcodeproj = $appName + '.xcodeproj'
$appXcworkspace = $appName + '.xcworkspace'
$fabricApiToken = 'fb931df74542114fa1c1ffbdfe87dadd77189efa'
$fabricBuildSecret = ENV['FABRIC_BUILD_SECRET']

############################# UTILITIES  ################################

def log message
    sh "echo " + message
end

def fatal message
  log message
  UI.user_error!(message)
end

def notify title, message
    notification subtitle: title, message: message, sound: "Purr"
end

def voice message
    say message
end

############################# VERSIONING ################################

def setVersion version
    log "Setting version to " + version
    sh "cd .. && xcrun agvtool new-version -all " + version, log: true
    sh "cd .. && xcrun agvtool new-marketing-version " + version, log: true
end

def incrementVersion projectFile, level
    log "Incrementing version " + level
    version = increment_version_number bump_type: level, xcodeproj: projectFile
    log "Incremented version to " + version
    setVersion version
end

############################# CERTIFICATES ################################

def certificates
#   sync_code_signing(type: "appstore")
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
end

############################# BUILD ################################

def build workspace, scheme
    build_app workspace: workspace, scheme: scheme
    notify "Finished Building", "Ready to upload..."
    voice "Build Complete"
end

############################# UPLOAD ################################

def upload target

  case target
  when "testfligkt"
    upload_to_testflight
  when "fabric"
    crashlytics api_token: $fabricApiToken, build_secret: $fabricBuildSecret
  else
    fatal "Unknown upload target " + target
  end

  notify "Finished Uploading", "Ready to test..."
  voice "Upload Complete"
end

############################# LANES ################################

def init
  if $fabricBuildSecret.nil? || $fabricBuildSecret.empty?
    fatal "FABRIC_BUILD_SECRET environment variable not set. Please set it using\nexport FABRIC_BUILD_SECRET='YOUR_FABRIC_BUILD_SECRET_KEY'"
  end
end

def makePandasHappy
    init
    certificates
    incrementVersion $appXcodeproj, "patch"
    build $appXcworkspace, $appName
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    makePandasHappy
    upload "testfligkt"
  end
  desc "Push a new beta build to Crashlytics"
  lane :fabric do
    makePandasHappy
    upload "fabric"
  end
end
